# Generated by Django 3.2 on 2021-04-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='max_time',
            field=models.IntegerField(help_text='minutes', verbose_name='Max Time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
