# Generated by Django 3.2 on 2021-05-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_detailresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailresult',
            options={'verbose_name': 'Detail Result', 'verbose_name_plural': 'Detail Results'},
        ),
        migrations.RemoveField(
            model_name='detailresult',
            name='answer_list',
        ),
        migrations.RemoveField(
            model_name='detailresult',
            name='question_id',
        ),
        migrations.AddField(
            model_name='detailresult',
            name='result_content',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Result Content'),
        ),
    ]
