# Generated by Django 3.2 on 2021-05-06 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20210505_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailresult',
            old_name='result_id',
            new_name='result',
        ),
        migrations.RemoveField(
            model_name='detailresult',
            name='result_content',
        ),
        migrations.AddField(
            model_name='detailresult',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.answer'),
        ),
        migrations.AddField(
            model_name='detailresult',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.question'),
        ),
    ]
